Repository vimtor/nuclio-minimalist-clone, pull requests merged in 2021-03, with the labels that each got.

#45 Completed tasks
  backend/src/index.js
  backend/src/repositories/list-repository.js
  backend/src/routers/auth-router.js
  backend/src/routers/chart-router.js
  backend/src/services/chart-service.js
  backend/src/services/user-service.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/app.js
  frontend/src/components/completed-tasks-chart/completed-tasks-chart.js
  frontend/src/components/completed-tasks-chart/completed-tasks-chart.options.js
  frontend/src/components/list-card/task-list/task-list.js
  frontend/src/components/lists-feed/lists-feed.js
  frontend/src/components/lists-feed/lists-feed.module.css
  frontend/src/components/profile-display/profile-display.css
  frontend/src/components/profile-display/profile-display.js
  frontend/src/components/protected-logged/protected-logged.js
  frontend/src/contexts/active-list-context.js
  frontend/src/contexts/chart-context.js
  frontend/src/helpers/api.js
  frontend/src/hooks/use-chart.js
  frontend/src/pages/login-page.js
  frontend/src/pages/login/login-page.js
  frontend/src/pages/login/login.module.css
  frontend/src/pages/profile/profile-page.js
  frontend/src/pages/profile/profile-page.module.css
  frontend/src/pages/register-page.js
  frontend/src/pages/register/register-page.js
  frontend/src/pages/register/register.module.css
Labels: enhancement

#61 Extract profile picture
  frontend/src/components/profile-display/profile-display.js
  frontend/src/components/profile-display/profile-display.module.css
  frontend/src/components/profile-image/profile-image.js
  frontend/src/components/profile-image/profile-image.module.css
Labels: Type: Feature

#64 default username like email (profile display)
  frontend/src/components/profile-display/profile-display.js
  frontend/src/helpers/api.js
Labels: Type: Bug

#65 fix error when no listId + CSS on message
  frontend/src/components/list-card/list-card.js
  frontend/src/components/list-card/list-card.module.css
  frontend/src/contexts/lists-context.js
Labels: Type: Bug

#66 CSS format "add new list" + avatar + "clear all"
  frontend/src/components/list-card/card-footer/card-footer.module.css
  frontend/src/components/lists-feed/lists-feed.module.css
  frontend/src/components/profile-image/profile-image.module.css
Labels: Type: Bug

#63 Fix register page block
  frontend/src/components/profile-display/profile-display.js
  frontend/src/contexts/auth-context.js
  frontend/src/pages/register/register-page.js
Labels: Type: Bug

#71 fixed loop variable in share-list.js component. Checked if list alre…
  backend/src/services/list-service.js
  frontend/src/components/modal/share-list/share-list.js
  frontend/src/components/profile-display/profile-display.js
Labels: Type: Bug
